name    'lfisher47-kernel'
version '0.0.3'
author  'Leah Fisher'
license 'Apache2'
project_page 'https://github.com/lfisher47/puppet-kernel'
source  'git://github.com/lfisher47/puppet-kernel'
summary 'PAM STIG requirements'
description 'PAM STIG requirements'
